# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-17 01:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagina',
            name='url',
            field=models.CharField(default='selecao', max_length=200),
            preserve_default=False,
        ),
    ]
