# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_sobre_ordem'),
    ]

    operations = [
        migrations.AddField(
            model_name='petiano',
            name='foto',
            field=models.FileField(default=1, upload_to='uploads/%Y/%m/%d/'),
            preserve_default=False,
        ),
    ]
