# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-19 00:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('downloads', '0002_arquivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='arquivo',
            name='pasta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='downloads.Pasta'),
            preserve_default=False,
        ),
    ]
