# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-17 01:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('selecao', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='selecao',
            options={'verbose_name': 'Seleção', 'verbose_name_plural': 'Seleção'},
        ),
    ]
