# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-17 22:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selecao', '0004_auto_20170717_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='arquivocpf',
            field=models.FileField(blank=True, upload_to='uploads/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='atividade',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='bolsa',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='orientador',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='projeto',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
