# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-02 02:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selecao', '0005_auto_20170717_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='atendimento_especial',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='candidato',
            name='auto_declaracao',
            field=models.FileField(blank=True, upload_to='uploads/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='candidato',
            name='comprovante_cad_unico',
            field=models.FileField(blank=True, upload_to='uploads/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='candidato',
            name='date_created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='candidato',
            name='necessita_atendimento_especial',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='candidato',
            name='nome_social',
            field=models.CharField(blank=True, max_length=500, verbose_name='Nome Social'),
        ),
        migrations.AddField(
            model_name='candidato',
            name='reserva_de_vagas',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='candidato',
            name='situacao_projeto',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='atividade',
            field=models.CharField(blank=True, max_length=300, verbose_name='Atividade Remunerada fora da UFAL'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='nome',
            field=models.CharField(max_length=500, verbose_name='Nome Civil'),
        ),
    ]
