# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-05-19 22:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selecao', '0006_auto_20190901_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='aceitou',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='atendimento_especial',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Tem problema com internet'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='atividade',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Atividade Remunerada fora da UFAL'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='bolsa',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='cpf',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='curso',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='email',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='endereco',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='estado_civil',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='local',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='mora_com',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='naturalidade',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='necessita_atendimento_especial',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='nome',
            field=models.CharField(max_length=1000, verbose_name='Nome Civil'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='nome_social',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Nome Social'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='orientador',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='periodo',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='projeto',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='reserva_de_vagas',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='rg',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='situacao_projeto',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='telefone',
            field=models.CharField(max_length=1000),
        ),
    ]
