# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-05-19 23:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selecao', '0008_auto_20200519_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='matricula',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
